---
apiVersion: v1
kind: Service
metadata:
  name: serviceName
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
   app: serviceName
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: serviceName
spec:
  replicas: 1
  template:
  metadata:
    labels:
    app: serviceName
  spec:
    containers:
    - name: serviceName
    image: vsl22acr.azurecr.io/serviceName:v0.2
    ports:
    - containerPort: 80
    envFrom:
      - configMapRef:
        name: the-configmap
    env:
    - name: ASPNETCORE_URLS
      value: http://*:80
    resources:
      limits: 
      cpu: 500m
      memory: 128Mi
    imagePullSecrets:
    - name: pullsecrets
  selector:
  matchLabels:
    app: serviceName
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: apiName
spec:
  replicas: 1
  template:
  metadata:
    labels:
    app: apiName
  spec:
    containers:
    - name: apiName
    image: vsl22acr.azurecr.io/apiName:v0.2
    ports:
    - containerPort: 80
    env:
    - name: ASPNETCORE_URLS
      value: http://*:80
    resources:
      limits: 
      cpu: 500m
      memory: 128Mi
    imagePullSecrets:
    - name: pullsecrets
  selector:
  matchLabels:
    app: apiName
---
apiVersion: v1
kind: Service
metadata:
  name: apiName
spec:
  type: ClusterIP
  ports:
  - port: 80
  selector:
  app: apiName
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: the-configmap
data:
  EnvName: my-ConfigMap